services:
  backend-dj:
    build:
      context: .

    ports:
      - "8000:8000"
    volumes:
      - ./service:/service  

    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass


    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000" 

    depends_on:
     - database


  database:
    image: postgres:15

    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
  redis:
    image: redis:7.2.4-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info 
    volumes:
      - ./service:/service  
    depends_on:
      - redis  
      - database

    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

  flower:  
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower

    depends_on:
      - redis  
    ports:
      - "1234:5555"


