# Generated by Django 5.0.1 on 2024-04-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('full', 'Full'), ('discount', 'Discount'), ('student', 'Student')], max_length=50),
        ),
    ]
